[package]
name = "browsercookie-rs"
version = "0.1.0"
authors = ["tunnelshade <tunnelshade@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
cookie = "0.11.0"
dirs = "1.0"
lz4 = "1.23.1"
memmap = "0.7.0"
rust-ini = "0.13.0"
serde = { version = "1.0.90", features = ["derive"]}
serde_json = "1.0.39"
regex = "1"
